# Generated by Django 4.1.4 on 2022-12-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='vaqt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
