# Generated by Django 4.1.4 on 2022-12-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_portfolio_vaqt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=20)),
                ('rasm1', models.ImageField(upload_to='media')),
                ('malumot', models.TextField()),
                ('vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('lavozim', models.CharField(max_length=30)),
                ('link_Twiter', models.CharField(max_length=100)),
                ('link_Facebook', models.CharField(max_length=100)),
                ('link_Instagram', models.CharField(max_length=100)),
                ('link_Index', models.CharField(max_length=100)),
                ('rasm1', models.ImageField(upload_to='media')),
                ('malumot', models.TextField()),
                ('vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
