# Generated by Django 4.1.4 on 2022-12-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0005_saqlash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saqlash',
            old_name='subjects',
            new_name='gmail',
        ),
    ]
